version: '3.7'

services:
  sls:
    image: rtainjapan/srt-live-server:master
    restart: always
    ports:
      - "8080:8080"
  ffmpeg:
    image: jrottenberg/ffmpeg:4.1-ubuntu
    entrypoint: bash
    #command: bash
    stdin_open: true
    tty: true
    working_dir: /root
    volumes:
      - ./:/root/external
