version: "3.7"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    restart: always
    ports:
      - "1935:1935"
      - "8085:8085"
      - "8086:8086"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/html/:/www/html/
